/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cadastrotriste;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edson_ficanha-jun
 */
public class Tela11 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tela11.class.getName());

    /**
     * Creates new form Tela1
     */
    public Tela11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCadastro = new javax.swing.JTable();
        TxtNomecpf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        TxtDataentrega = new javax.swing.JFormattedTextField();
        TxtCpf = new javax.swing.JFormattedTextField();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TxtValorproduto = new javax.swing.JTextField();
        TxtQuantidade = new javax.swing.JTextField();
        TxtMao = new javax.swing.JTextField();
        TxtValortotal = new javax.swing.JTextField();
        BtLimpar = new javax.swing.JButton();
        BtCalcular = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtCadastrar = new javax.swing.JButton();
        BtLimpa = new javax.swing.JButton();
        BtEditar = new javax.swing.JButton();
        BtSair = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel11.setText("Usuarios cadastrados:");

        jtCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "DATA DE ENTREGA", "VALOR TOTAL"
            }
        ));
        jScrollPane1.setViewportView(jtCadastro);

        TxtNomecpf.addActionListener(this::TxtNomecpfActionPerformed);

        jLabel12.setText("Digite Nome ou CPF, para realizar a consulta");

        jToggleButton1.setText("Pesquisar");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);

        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(TxtNomecpf, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jToggleButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel12))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(TxtNomecpf, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtNomecpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1)))
        );

        jLabel5.setText("Dados");

        jLabel6.setText("Nome:");

        jLabel7.setText("CPF:");

        jLabel8.setText("Data entrega:");

        try {
            TxtDataentrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtCpf.addActionListener(this::TxtCpfActionPerformed);

        jDesktopPane4.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(TxtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(TxtDataentrega, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(TxtCpf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(TxtDataentrega)
                    .addComponent(TxtCpf))
                .addContainerGap())
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtDataentrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel1.setText("Valores");

        jLabel2.setText("Valor produto:");

        jLabel3.setText("Quanti. de produtos:");

        jLabel9.setText("Mão de obra:");

        jLabel10.setText("Valor Total:");

        TxtValorproduto.addActionListener(this::TxtValorprodutoActionPerformed);

        BtLimpar.setText("Limpar");
        BtLimpar.addActionListener(this::BtLimparActionPerformed);

        BtCalcular.setText("Calcular");
        BtCalcular.addActionListener(this::BtCalcularActionPerformed);

        jDesktopPane5.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(TxtValorproduto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(TxtQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(TxtMao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(TxtValortotal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(BtLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(BtCalcular, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(1, 1, 1)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtValortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtMao, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtValorproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BtLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtCalcular)
                .addGap(46, 46, 46))
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtValorproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(jDesktopPane5Layout.createSequentialGroup()
                        .addComponent(TxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtMao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane5Layout.createSequentialGroup()
                        .addComponent(TxtValortotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtCalcular))
                    .addGroup(jDesktopPane5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(BtLimpar)))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(this::BtExcluirActionPerformed);

        BtCadastrar.setText("Cadastrar");
        BtCadastrar.addActionListener(this::BtCadastrarActionPerformed);

        BtLimpa.setText("Limpar");
        BtLimpa.addActionListener(this::BtLimpaActionPerformed);

        BtEditar.setText("Editar");
        BtEditar.addActionListener(this::BtEditarActionPerformed);

        BtSair.setText("Sair");
        BtSair.addActionListener(this::BtSairActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDesktopPane5)
                            .addComponent(jDesktopPane4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtLimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(BtEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDesktopPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDesktopPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDesktopPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtSair)
                        .addComponent(BtLimpa)
                        .addComponent(BtEditar)
                        .addComponent(BtExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparActionPerformed
TxtQuantidade.setText("");
TxtMao.setText("");
TxtValorproduto.setText("");
TxtValortotal.setText("");

    }//GEN-LAST:event_BtLimparActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
 int linha = jtCadastro.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um cadastro na tabela para excluir");
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente excluir este cadastro?",
                "Confirmando exclusao",
                JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            DefaultTableModel modelo
                    = (DefaultTableModel) jtCadastro.getModel();
            modelo.removeRow(linha);
            jtCadastro.clearSelection();
            JOptionPane.showMessageDialog(
                    this,
                    "Cadastro excluido com sucesso");
        }        
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
  if(TxtNome.getText().trim().isEmpty()){
  JOptionPane.showMessageDialog(
  this,
  "esse campo é obrigatorio!"       
  
  );
  
  TxtNome.requestFocus();
  return;
  }
  String cpf = TxtCpf.getText().replaceAll("[^0-9]","");
  if(cpf.isEmpty()|| cpf.length()!=11){
  JOptionPane.showMessageDialog(
  this, 
          "O CPF é obrigatorio!"
  );
  TxtCpf.requestFocus();
  return;
  
  }
  JOptionPane.showMessageDialog(
  this,
          "Nome e CPF preenchidos corretamente!"
  );
  
  DefaultTableModel modelo = (DefaultTableModel) jtCadastro.getModel();
  //Você ja tinha me avisado, que tem compromisso, eu sei o soltiado, mas o que vou fazer, depois do cochilo, amor será que vai sempre assim com você, tenho tanto aqui, pra te oferecer, pelo menos deixa eu te querer amor não me diz que essa nova paixão não sei o que
 int id = modelo.getRowCount()+1;
 String nome = TxtNome.getText();
    String data = TxtDataentrega.getText();
    String total = TxtValortotal.getText();
    
    modelo.addRow (new Object[]{
    id,
        nome,
        cpf,
        data,
        total
    });
    
    TxtValortotal.setText("");  
    TxtNome.setText("");  
    TxtCpf.setText("");  
    TxtDataentrega.setText("");  
     
    
    modelo.addRow(new Object[]{
    id,
    nome,
    cpf,
    data,
    total
    });
    
    TxtValortotal.setText("");
    TxtNome.setText("");
    TxtCpf.setText("");
    TxtDataentrega.setText("");
    
    TxtNome.requestFocus();
  //Fim
    }//GEN-LAST:event_BtCadastrarActionPerformed

    private void BtLimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimpaActionPerformed
TxtQuantidade.setText("");
TxtMao.setText("");
TxtValorproduto.setText("");
TxtValortotal.setText("");
TxtNome.setText("");
TxtCpf.setText("");
TxtDataentrega.setText("");
TxtNomecpf.setText("");
    }//GEN-LAST:event_BtLimpaActionPerformed

    private void BtEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEditarActionPerformed
int linha = jtCadastro.getSelectedRow();
        if (linha == 1) {
            JOptionPane.showMessageDialog(
                    this,
                    "Selecione um cadastro na tabela para alterar");
            return;
        }
        if (TxtDataentrega.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Informe a nova data de entrega"
            );
            TxtDataentrega.requestFocus();
            return;
        }
        DefaultTableModel modelo = (DefaultTableModel) jtCadastro.getModel();
        modelo.setValueAt(
                TxtDataentrega.getText(),
                linha,
                3);
        JOptionPane.showMessageDialog(
                this,
                "Data de entrega alterada com sucesso");
        TxtDataentrega.setText("");     
    }//GEN-LAST:event_BtEditarActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
    dispose();
    }//GEN-LAST:event_BtSairActionPerformed

    private void BtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCalcularActionPerformed
double quantidade = Double.parseDouble(TxtQuantidade.getText());
double produto = Double.parseDouble(TxtValorproduto.getText());
double mao =Double.parseDouble(TxtMao.getText());

//Calcula a quantidade x valor do produto + a mão de oba
double total = (quantidade * produto)+mao;

//Mostra o resultado do campo total
TxtValortotal.setText(String.valueOf(total));
    }//GEN-LAST:event_BtCalcularActionPerformed

    private void TxtValorprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtValorprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtValorprodutoActionPerformed

    private void TxtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCpfActionPerformed

    private void TxtNomecpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomecpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomecpfActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
String pesquisa = TxtNomecpf.getText().trim();
if(pesquisa.isEmpty()){
JOptionPane.showMessageDialog(
this,
        "Digite um nome ou CPF para pesquisar!"
);
TxtNomecpf.requestFocus();
return;

}
DefaultTableModel modelo = (DefaultTableModel) jtCadastro.getModel();
boolean encontrado = false;
for (int i = 0; i < modelo.getRowCount(); i++){
    String nome = modelo.getValueAt(i, 1).toString();
    
    String cpf = modelo.getValueAt (i, 2).toString();
    if (nome.toLowerCase().contains(pesquisa.toLowerCase())
            || cpf.contains(pesquisa)) {
    jtCadastro.setRowSelectionInterval(i, i);
    encontrado = true;
    break;
    }
    }
//se não encontrou
if(!encontrado){
JOptionPane.showMessageDialog(
this,
        "informe a nova data de entrega"
);

    }

//fim
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela11().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JButton BtCalcular;
    private javax.swing.JButton BtEditar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtLimpa;
    private javax.swing.JButton BtLimpar;
    private javax.swing.JButton BtSair;
    private javax.swing.JFormattedTextField TxtCpf;
    private javax.swing.JFormattedTextField TxtDataentrega;
    private javax.swing.JTextField TxtMao;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNomecpf;
    private javax.swing.JTextField TxtQuantidade;
    private javax.swing.JTextField TxtValorproduto;
    private javax.swing.JTextField TxtValortotal;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable jtCadastro;
    // End of variables declaration//GEN-END:variables
}
